### ISSUE TITLE
consider using accessible-output2  for streaming chat messages.

### ISSUE THREAD

**Issue by rperez030** [SigmaNight/basiliskLLM#114]
Currently, keyboard focus moves to the messages field when a new response is generated and it is necessary to use the arrow key to read the entire response. It may be interesting to try to duplicate the user experience of the NVDA add-on in this area, and the [accessible-output2 library](https://pypi.org/project/accessible-output2/) may be the way to do it so that the experience is comparable with both JAWS and NVDA.

**Comment by rperez030** [comment]
Sure! I don't have too much time these days, but as long as we're ok with keeping it as a low priority item, I'll get to it as soon as I can.

**Comment by aaclause** [comment]
Hi @rperez030, I wanted to check on the status of this issue. Let me know if you need any help or if there are updates to share! :)

**Comment by AAClause** [comment]
Hi @rperez030,

Thank you for your initial interest in implementing this feature. Since we've not heard back after several months, we will proceed with it ourselves to maintain progress.

We appreciate your understanding and look forward to any future contributions you may have.

**Comment by rperez030** [comment]
Thank you for taking on that task. I considered implementing something like UiaRaiseNotificationEvent to maintain screen reader agnosticism, but it turned out to be more challenging than I anticipated, and I didn't find the time to make progress. I love how much the project is growing and look forward to contributing in the future.

Thank you very much for all your hard work and dedication.
