### ISSUE TITLE
Remember the last model used when exiting the application

### ISSUE THREAD

**Issue by Nael-Sayegh** [SigmaNight/basiliskLLM#273]
Currently, when basiliskllm is opened, the conversation model is not set by default. When one is selected, a conversation is held, and the application is closed, the model is not saved. As a result, upon reopening the program, the model needs to be selected again. Is this the expected behavior?

**Comment by aaclause** [comment]
@Nael-Sayegh Quick test: the "Top P" field/label is broken, and is also labeled as "Max tokens".

**Comment by aaclause** [comment]
Yes, that is the current behavior when no default profile is defined. However, your suggestion deserves some thought

**Comment by Nael-Sayegh** [comment]
Thank you, I created a default profile and that solves my problem. Since setting a default model would be a bit complicated, especially with regards to using different tabs, I suggest we close this issue. 
@AAClause What do you think?
