### ISSUE TITLE
Pixtral (pixtral-12b-2409) problem

### ISSUE THREAD

**Issue by MH140000** [SigmaNight/basiliskLLM#292]
hello I used this model. Problems:
1. The texts are very messed up.
2. There is a problem changing the language. For example, I talk to him in Farsi, and once the model's language changes to Turkish.

Thank you again for your very good software.

**Comment by MH140000** [comment]
For example, repeats an unrelated word 1000 times.

**Comment by MH140000** [comment]
Of course, I think the problem is not with basiliskLLM software but with the model.

**Comment by AAClause** [comment]
Hello, thanks for your feedback!

On my side, I have had rather good results in the French language.

It appears that Pixtral is built upon Mistral NeMo¹. Also, Mistral NeMo is known for its strong performance in English, French, German, Spanish, Italian, Portuguese, Chinese, Japanese, Korean, Arabic, and Hindi². From what I've read, Farsi is similar to Arabic in some ways but still different, right?

¹: [Announcing Pixtral 12B](https://mistral.ai/news/pixtral-12b/) 
²: [Mistral NeMo](https://mistral.ai/news/mistral-nemo/)

**Comment by MH140000** [comment]
Yes, it's true, I use Persian language easily with Mistral Large, but I have problems with this model. I don't know where the problem is.
